variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
- test
- build

perl_critic:
  stage: test
  image: olegfiksel/perl_critic:latest
  script:
    - critichtml *.pl
    - critictext *.pl
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
    - critic_html

perl_test_perlver:
  stage: test
  image: olegfiksel/perl_critic:latest
  script:
    - test_perlver *.pl

lint:dockerfile:
  stage: test
  image: hadolint/hadolint:latest-debian
  script:
    - |
      bash -c '
      for i in $(find . -name Dockerfile); do
        echo -n "hadolint: Checking $i ... "
        hadolint $@ $i
        retcode=$?
        if [[ "$retcode" != 0 ]]; then
          echo "Error ($retcode)!"
          exit ${retcode}
        else
          echo "Done!"
        fi
      done
      '

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  tags:
    - dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^v\d+/

